server:
  port: 0
  error:
    include-message: always
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-ext
---
spring:
  profiles: development, default
server:
  port: 8008
