package de.immomio.openimmo.typen;

/**
 * @author Fabian Beck
 */

public enum OpenImmoZustandArtTyp {
    ERSTBEZUG, TEIL_VOLLRENOVIERUNGSBED, NEUWERTIG, TEIL_VOLLSANIERT, TEIL_VOLLRENOVIERT, TEIL_SANIERT, VOLL_SANIERT, SANIERUNGSBEDUERFTIG, BAUFAELLIG, NACH_VEREINBARUNG, MODERNISIERT, GEPFLEGT, ROHBAU, ENTKERNT, ABRISSOBJEKT, PROJEKTIERT,
}
