package de.immomio.openimmo.typen;

/**
 * @author Fabian Beck
 */

public enum OpenImmoParkenTyp {
    STELLPLATZ, CARPORT, DOPPELGARAGE, DUPLEX, TIEFGARAGE, BOOTSLIEGEPLATZ, EINZELGARAGE, PARKHAUS, TIEFGARAGENSTELLPLATZ, PARKPLATZ_STROM
}
