package de.immomio.openimmo.typen;

/**
 * @author Fabian Beck
 */

public enum OpenImmoDistanzenTyp {
    FLUGHAFEN, FERNBAHNHOF, AUTOBAHN, US_BAHN, BUS, KINDERGAERTEN, GRUNDSCHULE, HAUPTSCHULE, REALSCHULE, GESAMTSCHULE, GYMNASIUM, ZENTRUM, EINKAUFSMOEGLICHKEITEN, GASTSTAETTEN
}
