package de.immomio.openimmo.typen;

/**
 * @author Fabian Beck
 */

public enum OpenImmoHausTyp {
    REIHENHAUS, REIHENEND, REIHENMITTEL, REIHENECK, DOPPELHAUSHAELFTE, EINFAMILIENHAUS, STADTHAUS, BUNGALOW, VILLA, RESTHOF, BAUERNHAUS, LANDHAUS, SCHLOSS, ZWEIFAMILIENHAUS, MEHRFAMILIENHAUS, FERIENHAUS, BERGHUETTE, CHALET, STRANDHAUS, LAUBE_DATSCHE_GARTENHAUS, APARTMENTHAUS, BURG, HERRENHAUS, FINCA, RUSTICO, FERTIGHAUS, KEINE_ANGABE,
}
