package de.immomio.model.repository.shared.selfdisclosure;

import de.immomio.model.repository.core.shared.selfdisclosure.BaseSelfDisclosureSubQuestionConfigurationRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface SelfDisclosureSubQuestionConfigurationRepository extends BaseSelfDisclosureSubQuestionConfigurationRepository {
}
